# Generated by Django 5.2.1 on 2025-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
