# Generated by Django 5.2.1 on 2025-05-17 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_contact_user_service_category_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_services',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.service'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_categories',
            field=models.ManyToManyField(blank=True, related_name='managers', to='myapp.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
